{
 "title": "Sense Collector - Collector Info",
 "description": "Sense Collector provides a way of collecting real-time data from the Sense Energy Monitor. These Grafana dashboards offer visualizations for detected devices and smart plugs and their wattage, voltage, and amp utilization.",
 "tags": [
  "sense-collector",
  "influxdb"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_hostname",
    "label": "Host",
    "query": "select DISTINCT(\"host_hostname\") from (select \"host_hostname\",\"cpu_soft\" from \"sense_o11y\" WHERE $timeFilter)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "SHOW TAG VALUES FROM \"sense_o11y\" WITH KEY = \"source\""
   },
   {
    "name": "function",
    "label": "Function",
    "query": "SHOW TAG VALUES FROM \"sense_o11y\" WITH KEY = \"function\" WHERE \"source\" =~ /^$source$/"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,10s,15s,30s,1m,5m,10m,15m,1h,3h"
   }
  ]
 },
 "panels": [
  { "title": "Collector Duration Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Function Timer",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_source - $tag_function",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "function" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$source$/" },
      { "condition": "AND", "key": "function", "operator": "=~", "value": "/^$function$/" }
     ]
    }
   ]
  },
  {
   "title": "Epoch Time Difference",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_source - $tag_function",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "function" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "select": [
      [
       { "params": [ "difference_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$source$/" },
      { "condition": "AND", "key": "function", "operator": "=~", "value": "/^$function$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Observability - $host_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "collector_key"
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"sense_o11y\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "cpu_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "IO Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"sense_o11y\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "loadavg_one" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_five" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_fifteen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Process CPU Usage (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_sysperf_command",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sysperf_command" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysperf_type", "operator": "=", "value": "process_utilization" }
     ]
    }
   ]
  },
  {
   "title": "Netstat (Container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_netstat_app - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "netstat_app" ], "type": "tag" }
     ],
     "measurement": "sense_o11y",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"sense_o11y\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "netstat_closewait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Close Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Established" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_finwait2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Finwait2" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_listen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Listen" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_timewait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Timewait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "sysperf_type", "operator": "=", "value": "netstat" }
     ]
    }
   ]
  },
  {
   "title": "Processes (Container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"sense_o11y\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "processes_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_zombie" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Zombie" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sense_o11y",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"sense_o11y\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_buffers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffers" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_cache" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_shared" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Collector Socket Refresh Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sense_event",
     "select": [
      [
       { "params": [ "time_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "event_type", "operator": "=", "value": "hello" }
     ]
    }
   ]
  },
  {
   "title": "Collector Starts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "sense_o11y",
     "select": [
      [
       { "params": [ "time_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "event" }
     ]
    }
   ]
  },
  {
   "title": "Collector Start Time",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "sense_o11y",
     "select": [
      [
       { "params": [ "time_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "event" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "event" }
     ]
    }
   ]
  }
 ]
}